//import image from './images/d1.jpg';

export default {
    products: [
        {
            _id: '1',
            name: 'Slim Shirt',
            category: 'Shirts',
            image: './images/d1.jpg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
        },
        {
            _id: '2',
            name: 'Fit Shirt',
            category: 'Shirts',
            image: './images/d1.jpg',
            price: 50,
            brand: 'Nike',
            rating: 4,
            numReviews: 8,
        },
        {
            _id: '3',
            name: 'Best Pants',
            category: 'Pants',
            image: './images/d1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 5,
            numReviews: 9,
        },
        {
            _id: '4',
            name: 'Shirt',
            category: 'Shirts',
            image: './images/d1.jpg',
            price: 20,
            brand: 'Lacoste',
            rating: 5,
            numReviews: 9,
        },
        {
            _id: '5',
            name: 'Jeans',
            category: 'Pants',
            image: './images/d1.jpg',
            price: 40,
            brand: 'Forever 21',
            rating: 3,
            numReviews: 11,
        },
        {
            _id: '6',
            name: 'Joggings',
            category: 'Pants',
            image: './images/d1.jpg',
            price: 20,
            brand: 'Adidas',
            rating: 4,
            numReviews: 13,
        },
    ],
};
